test:
    hello: "exception"
    args: "args{0}{1}"

api:
    exception:
        DuplicatedEmailException:
            message: "중복된 이메일입니다!!"
        UndefinedException:
            message: "알 수 없는 에러입니다."